### ISSUE TITLE
[Feature] Criar relação 1:n de Produtos e Categorias

### ISSUE THREAD

**Issue by Igor-Mont** [softeam-org/bar-cultural-back-end#13]
- Adicionar a relação n:m de produtos para categorias.
- Garantir que os testes funcionam.
- Testar as novas features nos testes.

**Comment by ArthurHenriqueSilva** [comment]
Devo referenciar as tabelas pelos nomes da categoria e produto, ou pelos seus ID`s ?

**Comment by ArthurHenriqueSilva** [comment]
Pra definir a relacao de muitos na table category, fiz um array de Product[]. Como referencio esse coluna no create-category.dto.ts ? Nao consigo dar push porque o codigo esta com erro. Alem disso, essa task envolve alterar o schema.prisma, os create...dtos, entities, model do product, specs e os arquivos correspondentes da pasta test, correto ?

**Comment by Igor-Mont** [comment]
> Pra definir a relacao de muitos na table category, fiz um array de Product[]. Como referencio esse coluna no create-category.dto.ts ? Nao consigo dar push porque o codigo esta com erro. Alem disso, essa task envolve alterar o schema.prisma, os create...dtos, entities, model do product, specs e os arquivos correspondentes da pasta test, correto ?

Eu defini erroneamente a relação dessa tabela acho que isso fez com que você entendesse mal também, a relação é de n:m, vai ser necessária a criação de uma nova tabela para armazenar isso.

- product_id
- category_id

**Comment by ArthurHenriqueSilva** [comment]
![image](https://github.com/softeam-org/bar-cultural-back-end/assets/115894179/a3aff783-ca72-493c-97e2-a05b4408d9bd)
![image](https://github.com/softeam-org/bar-cultural-back-end/assets/115894179/997b56e0-f3a2-413e-bbc1-7d22aaea7ccb)
![image](https://github.com/softeam-org/bar-cultural-back-end/assets/115894179/a1d1d89d-3d87-47d6-bb17-a36c16bf603e)
Esse construtor de const category esta sendo definido em qual arquivo ? O mesmo erro ocorre com os products.

**Comment by ArthurHenriqueSilva** [comment]
No aguardo desse direcionamento para prosseguir com o projeto. Esse erro está me travando para continuar porque não consigo nem compilar. Eu acredito que alem de gerar a migrate com o novo model, deva mais alguma ação para atualizar as dependências de acordo com a mudança do modelo. Se precisar de mais prints de código, eu mando.

**Comment by ArthurHenriqueSilva** [comment]
Vitor me ajudou no erro acima. Avancando para escrita dos testes.
