### ISSUE TITLE
[Fix] Entidade Produto

### ISSUE THREAD

**Issue by Igor-Mont** [softeam-org/bar-cultural-back-end#20]
- Um produto será linkado a uma e somente a uma categoria
  - Ou seja, o produto terá uma propriedade `category_id`
- Adicionar propriedade `amount_in_stock` que é a quantidade daquele produto disponível no estoque.
- Adicionar propriedade `is_active ` -> flag para indicar se a categoria está ou não ativa;

**Comment by ArthurHenriqueSilva** [comment]
No campo is_active, quer que coloque a inicialização default no model ? 
`is_active   Boolean @default(true)`
