### ISSUE TITLE
[Feature] CRUD vendedor

### ISSUE THREAD

**Issue by 0vitor** [softeam-org/bar-cultural-back-end#26]
- Adicionar documentação com o Swagger;
- Adicionar decorators com validação (`As libs class-validator e class-transformer já estão instaladas para isso.`);

## Create `(/seller)`

Body (JSON):

- cpf
- password

## Update `(/seller/:id)`

- Route param: `id` 

Body (JSON):

- cpf
- password

## Get `(/seller)`

- Listar todas os sellers

## Get `(/seller/:id)`

- Route param: `id`

- Listar o sellers com o `ìd` especificado.

## Delete `(/seller/:id)`

- Route param: `id`

**Comment by ArthurHenriqueSilva** [comment]
No caso,  o id mencionado em update e get seria o 'cpf' ?

**Comment by ArthurHenriqueSilva** [comment]
Alguma restrição para a senha ? Exemplo: Tamanho mínimo, necessidade de números, letras e caracteres especiais...

**Comment by ArthurHenriqueSilva** [comment]
Sugestão: Colocar campos created_at e updated_at no seller. 
Aguardo aprovação.

**Comment by ArthurHenriqueSilva** [comment]
Questões respondidas por @Jorgeloch :
No caso, o id mencionado em update e get seria o 'cpf' ? O id para funcionário será o cpf.
Alguma restrição para a senha ?  sem restrições
Colocar campos created_at e updated_at no seller: Pode adicionar
